server:
  port: 9527

spring:
  application:
    name: Twitter-collector
  datasource:
    url: jdbc:mysql://localhost:3308/twitter?useUnicode=true&characterEncoding=utf8&character_set_server=utf8mb4&useSSL=false
    username: root
    password: dreamworld
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

configFilename: privateConfig.yml
#是否在墙内，如果该值为true，会读取私有配置文件中的代理数据，目前已改为用命令行方式实现
blocked: false
swagger:
  enable: false