twitter4j:
  oauth:
    consumerKey: HahjE4eyFPsL0ZBUCqEnn23NM
    consumerSecret: duvRbF5t6LwUX3snKCx4o85GxciO6xs1rLOvU0L4fnkZM0ueF3
    accessToken: 1159802509-p859PqW1FYCmA1jSuoD7g46765SSGwAC3iKw2ne
    accessTokenSecret: pqtGhTB6rv4kKNjckXFn5bpYUA3OZGB3neqxL7jYedqek

#所有值均小写
proxy:
  type: "socks"
  host: "127.0.0.1"
  port: 1080
  user: null
  password: null